### ISSUE TITLE
Dataset-amalgamator: combination methods

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etlocal#464]
For the dataset amalagamator we have 3 different combination methods to aggregate datasets:

1. Adding
2. Averaging
3. Weighted averaging

In most cases where adding is not possible we need a weighted average, example: 

```
- header: industry_chemical_residual_heat
    type: slider
    combination_method:
      weighted_average:
        - input_industry_chemical_other_network_gas_demand
    items:
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_processes_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_flue_gasses_potential_residual_heat_parent_share
        unit: '%'
      - key: industry_useful_demand_for_chemical_other_useable_heat_industry_chemicals_other_used_heat_parent_share
        unit: '%'
        flexible: true
        skip_validation: true
```

The given key (`input_industry_chemical_other_network_gas_demand`) is used to define the weighted average. However, when this key is zero, the weighted average also automatically becomes zero. We do not want this as sometimes we want to keep a certain share even though the demand is not there.

**Proposal:** if a weighted average is given for a certain (set of) keys and the given key is 0.0 in all cases, it needs to revert to the 'average'. In other words, if the sum = 0.0 then revert back to 'average' method.

(see b34ef8d7911151dcca86747703d9691951c631c7 on the dataset-amalgamator for temporary fix)
