### ISSUE TITLE
Export to ETSource goes wrong because of shares in useful heat demand interface elements

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etlocal#510]
The values of the recently added (https://github.com/quintel/etlocal/pull/503) interface elements for share of useful heat per residence type and construction period lead to errors when exported to ETSource. For example, when I export GM0085, the following changes show up:

<img width="750" alt="Screenshot 2024-03-20 at 10 56 59" src="https://github.com/quintel/etlocal/assets/67338510/f518a8da-568c-41b7-ba3c-5d51c43d1486">

These seem like minor changes regarding the number of decimals. However, apparently they don't sum to exactly 1, causing refinery to produce an error:

<img width="750" alt="Screenshot 2024-03-20 at 10 56 44" src="https://github.com/quintel/etlocal/assets/67338510/7893aa04-fae9-4396-b21c-8a2ccfad1320">

This should not happen since one of the shares is flexible:
```yaml
      - key: input_present_share_of_terraced_houses_2005_present_in_useful_demand_for_space_heating
        unit: '%'
        combination_method:
          weighted_average:
            - present_number_of_terraced_houses_2005_present
        flexible: true
        skip_validation: true
```

The issue however is likely that the values are entered as percentage, while ETLocal interprets the interface elements as factors. This shows in the frontend, where 12.13 is read as 1213% and therefore exceeds the slider max:

<img width="750" alt="Screenshot 2024-03-20 at 11 00 04" src="https://github.com/quintel/etlocal/assets/67338510/1c40104a-c6cc-49a2-84ef-fd8b6eedfa0d">

We should write a migration fixing these interface element values, check whether they are handled properly by ETSource through SGQs after the fix and then see if the issue itself no longer occurs. Notifying @Charlottevm.
